### ISSUE TITLE
Red barrier is only partially removed

### ISSUE THREAD

**Issue by HobbitPower** [MT-CTF/maps#319] opened 2023-11-23 10:44 UTC
The bottom layers of the red barrier are not removed at the start of the round when testing in a **local** world. This is not noticeable on maps whose lowest layers are filled with stone, for example, but on maps such as **Water Academy** and **The Stone Maze** (PR #299). This also occurred when creating a map myself, even after re-saving several times. Water Academy is added to the server and this does not occur in-game afaik. Nevertheless, it would be good to know whether new maps can be merged without hesitation.

A striking feature of all maps in map version 3 (including those currently on the server) is that the second (smaller) y-coordinate always has the value 16 instead of 0: 
![image](https://github.com/MT-CTF/maps/assets/76528136/dd2f2e55-2e5f-4fb0-9ecc-f87da96f7390)

**Comment by LoneWolfHT** [comment] 2023-11-26 17:32
It's safe to merge maps. I think the issue is fixed now too

**Closed** 2023-11-30 12:06 UTC
